version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
