version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: giftlist
      POSTGRES_USER: gift
      POSTGRES_PASSWORD: Sab1XP7MgeRv3Tm
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
